### ISSUE TITLE
Question around quickstart compatiblity

### ISSUE THREAD

**Issue by BandoftheHawk** [benc-uk/azure-armviewer#5]
Hi,
Awesome project by the way. I was initially thinking of trying to do an implementation of the _Arm viewer for VS code_ for the browser, but on finding this my life is a whole lot easier :).

**Anyway, my question is:**
I noticed you wrote in the _Arm viewer for VS code_ repo README.md that "Extension has been tested successfully against all 900+ Azure Quickstart Templates 😁" so since this project hasn't really been updated in a few months, so I was just curious if this project in its current state would have a similar compatibility level.  Or if you have you made a lot of additional compatibility updates since Feb (your last update here) on the VSC extension implementation of this, that aren't present in this build?

Thanks alot!

**Comment by benc-uk** [comment]
This project came first, the plan was to port this code to work as VSC extension really as a proof of concept, and I intended on making as few changes as possible.

The extension turned out to be quote popular and so I made a LOT of changes and added a lot of features that are now only in the VSC extension code base :(

I could port/transfer those changes back here, the core changes are in the template parser and that's been keep fairly standalone. It might not be much work, but it's not something currently high on my priority list
